#!/bin/bash

#ENABLE PACKET FORWARD
echo 1 > /proc/sys/net/ipv4/ip_forward

#YOU COULD JUST ENABLE FORWARD FOR EVERYTHING WITHOUT LIMITATIONS, USING INTERFACES JUST TO BE MORE SPECIFIC
iptables -A FORWARD -i enp5s0 -o wlp3s0 -j ACCEPT
iptables -A FORWARD -i wlp3s0 -o enp5s0 -j ACCEPT

#MASQUERADE OUTBOUND CONNECTIONS
iptables -t nat -A POSTROUTING -o wlp3s0 -j MASQUERADE
